[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/mob-api/Dockerfile"
buildContext = "backend/mob-api"

[deploy]
startCommand = "php artisan package:discover --ansi && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
