[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/mob-api/Dockerfile"
buildContext = "backend/mob-api"

[deploy]
startCommand = "/bin/sh -c 'cd /var/www && php artisan migrate --force 2>&1; php artisan serve --host=0.0.0.0 --port=$PORT'"
